# Generated by Django 5.2.17 on 2026-09-29 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0002_alter_odometerreading_source_alter_vehicle_fuel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "km_ahead",
                    models.PositiveIntegerField(
                        default=1000,
                        validators=[django.core.validators.MaxValueValidator(20000)],
                        verbose_name="Avisar quando faltar (km)",
                    ),
                ),
                (
                    "days_ahead",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(365)],
                        verbose_name="Avisar quando faltar (dias)",
                    ),
                ),
                (
                    "reading_reminder_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Lembrar de atualizar o km após (dias)",
                    ),
                ),
                (
                    "show_high",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar alertas de prioridade alta"
                    ),
                ),
                (
                    "show_medium",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar alertas de prioridade média"
                    ),
                ),
                (
                    "show_low",
                    models.BooleanField(
                        default=True, verbose_name="Mostrar alertas de prioridade baixa"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="O que fazer")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oil", "Óleo e filtro de óleo"),
                            ("filters", "Filtros de ar, combustível e cabine"),
                            ("brakes", "Freios"),
                            ("tires", "Pneus, alinhamento e balanceamento"),
                            ("suspension", "Suspensão e direção"),
                            ("cooling", "Arrefecimento"),
                            ("battery", "Bateria"),
                            ("electrical", "Sistema elétrico e iluminação"),
                            ("engine", "Motor"),
                            ("transmission", "Transmissão e embreagem"),
                            ("fuel", "Combustível e injeção"),
                            ("belts", "Correias e componentes auxiliares"),
                            ("ac", "Ar-condicionado e ventilação"),
                            ("audio", "Sistema de som"),
                            ("body", "Carroceria, vedações, pintura e acabamento"),
                            ("general", "Revisão ou inspeção geral"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Recomendação do fabricante"),
                            ("usage", "Preventiva pelo uso"),
                            ("inspection", "Inspeção sugerida"),
                            ("diagnosis", "Precisa de diagnóstico profissional"),
                        ],
                        default="usage",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        max_length=8,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Por que fazer"
                    ),
                ),
                (
                    "interval_km",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500000),
                        ],
                        verbose_name="A cada (km)",
                    ),
                ),
                (
                    "interval_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(240),
                        ],
                        verbose_name="A cada (meses)",
                    ),
                ),
                (
                    "next_km",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                        verbose_name="Próxima vez (km)",
                    ),
                ),
                (
                    "next_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima vez (data)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("scheduled", "Programada"),
                            ("done", "Realizada"),
                            ("dismissed", "Descartada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateField(
                        blank=True, null=True, verbose_name="Programada para"
                    ),
                ),
                (
                    "dismissed_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Motivo do descarte"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Custo estimado (R$)",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=200, verbose_name="Fonte"),
                ),
                (
                    "source_verified",
                    models.BooleanField(
                        default=False, verbose_name="Conferi esta informação na fonte"
                    ),
                ),
                (
                    "suggestion_key",
                    models.CharField(blank=True, editable=False, max_length=40),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Observações"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="garage.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["title", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("suggestion_key", ""), _negated=True),
                        fields=("vehicle", "suggestion_key"),
                        name="one_plan_per_suggestion",
                    )
                ],
            },
        ),
    ]
