# Generated by Django 5.2.17 on 2026-09-23 01:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=80, verbose_name="Marca")),
                ("model", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "version",
                    models.CharField(blank=True, max_length=100, verbose_name="Versao"),
                ),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1886),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Ano de fabricacao",
                    ),
                ),
                (
                    "model_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1886),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Ano-modelo",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Motorizacao informada"
                    ),
                ),
                (
                    "engine_verified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Motorizacao conferida na documentacao",
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("unknown", "A confirmar"),
                            ("flex", "Flex"),
                            ("gasoline", "Gasolina"),
                            ("ethanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("electric", "Eletrico"),
                            ("hybrid", "Hibrido"),
                            ("other", "Outro"),
                        ],
                        default="unknown",
                        max_length=12,
                        verbose_name="Combustivel",
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de aquisicao"
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Placa (opcional)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        verbose_name="Observacoes e perfil de uso",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["brand", "model", "pk"],
            },
        ),
        migrations.CreateModel(
            name="OdometerReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Data da leitura",
                    ),
                ),
                (
                    "kilometers",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                        verbose_name="Quilometragem (km)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("panel", "Painel do veiculo"),
                            ("document", "Documento ou comprovante"),
                            ("history", "Historico informado"),
                        ],
                        default="panel",
                        max_length=12,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Observacao (opcional)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="garage.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle", "date"), name="one_reading_per_vehicle_day"
                    )
                ],
            },
        ),
    ]
