# Generated by Django 5.2.17 on 2026-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odometerreading",
            name="source",
            field=models.CharField(
                choices=[
                    ("panel", "Painel do veículo"),
                    ("document", "Documento ou comprovante"),
                    ("history", "Histórico informado"),
                    ("service", "Registro de serviço"),
                ],
                default="panel",
                max_length=12,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel",
            field=models.CharField(
                choices=[
                    ("unknown", "A confirmar"),
                    ("flex", "Flex"),
                    ("gasoline", "Gasolina"),
                    ("ethanol", "Etanol"),
                    ("diesel", "Diesel"),
                    ("electric", "Elétrico"),
                    ("hybrid", "Híbrido"),
                    ("other", "Outro"),
                ],
                default="unknown",
                max_length=12,
                verbose_name="Combustivel",
            ),
        ),
    ]
