# Generated by Django 5.2.17 on 2026-09-29 14:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0002_alter_odometerreading_source_alter_vehicle_fuel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symptom",
                    models.CharField(
                        choices=[
                            ("noise", "Ruído"),
                            ("vibration", "Vibração"),
                            ("warning_light", "Luz no painel"),
                            ("starting", "Dificuldade na partida"),
                            ("consumption", "Alteração no consumo"),
                            ("malfunction", "Falha de funcionamento"),
                            ("leak", "Vazamento"),
                            ("electrical", "Problema elétrico"),
                            ("wear", "Desgaste visual ou estrutural"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="O que você percebeu?",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Título curto"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=5000, verbose_name="Descreva com suas palavras"
                    ),
                ),
                (
                    "reported_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Quando percebeu"
                    ),
                ),
                (
                    "kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                        verbose_name="Quilometragem (km)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Onde no carro"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oil", "Óleo e filtro de óleo"),
                            ("filters", "Filtros de ar, combustível e cabine"),
                            ("brakes", "Freios"),
                            ("tires", "Pneus, alinhamento e balanceamento"),
                            ("suspension", "Suspensão e direção"),
                            ("cooling", "Arrefecimento"),
                            ("battery", "Bateria"),
                            ("electrical", "Sistema elétrico e iluminação"),
                            ("engine", "Motor"),
                            ("transmission", "Transmissão e embreagem"),
                            ("fuel", "Combustível e injeção"),
                            ("belts", "Correias e componentes auxiliares"),
                            ("ac", "Ar-condicionado e ventilação"),
                            ("audio", "Sistema de som"),
                            ("body", "Carroceria, vedações, pintura e acabamento"),
                            ("general", "Revisão ou inspeção geral"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="Sistema relacionado",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("unknown", "Não sei avaliar"),
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                        ],
                        default="unknown",
                        max_length=8,
                        verbose_name="Gravidade percebida",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("monitoring", "Em observação"),
                            ("diagnosis", "Em diagnóstico"),
                            ("resolved", "Resolvido"),
                            ("closed", "Encerrado sem conclusão"),
                        ],
                        default="open",
                        max_length=12,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        verbose_name="Diagnóstico realizado",
                    ),
                ),
                (
                    "ruled_out",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        verbose_name="Causas já descartadas",
                    ),
                ),
                (
                    "solution",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Solução aplicada"
                    ),
                ),
                (
                    "resolved_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resolvido em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="garage.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("reported_on"), descending=True, nulls_last=True
                    ),
                    "-pk",
                ],
            },
        ),
        migrations.CreateModel(
            name="ProblemUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Aberto"),
                            ("monitoring", "Em observação"),
                            ("diagnosis", "Em diagnóstico"),
                            ("resolved", "Resolvido"),
                            ("closed", "Encerrado sem conclusão"),
                        ],
                        max_length=12,
                        verbose_name="Nova situação",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="O que aconteceu?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="maintenance.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("oil", "Óleo e filtro de óleo"),
                            ("filters", "Filtros de ar, combustível e cabine"),
                            ("brakes", "Freios"),
                            ("tires", "Pneus, alinhamento e balanceamento"),
                            ("suspension", "Suspensão e direção"),
                            ("cooling", "Arrefecimento"),
                            ("battery", "Bateria"),
                            ("electrical", "Sistema elétrico e iluminação"),
                            ("engine", "Motor"),
                            ("transmission", "Transmissão e embreagem"),
                            ("fuel", "Combustível e injeção"),
                            ("belts", "Correias e componentes auxiliares"),
                            ("ac", "Ar-condicionado e ventilação"),
                            ("audio", "Sistema de som"),
                            ("body", "Carroceria, vedações, pintura e acabamento"),
                            ("general", "Revisão ou inspeção geral"),
                            ("other", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="O que foi feito"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Data")),
                (
                    "kilometers",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(9999999)],
                        verbose_name="Quilometragem (km)",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unspecified", "Não classificado"),
                            ("preventive", "Preventiva"),
                            ("corrective", "Corretiva"),
                            ("inspection", "Inspeção ou avaliação"),
                        ],
                        default="unspecified",
                        max_length=12,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "workshop",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Oficina ou profissional",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Descrição"
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Peças (R$)",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Mão de obra (R$)",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor total (R$)",
                    ),
                ),
                (
                    "warranty_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Garantia até"
                    ),
                ),
                (
                    "warranty_notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Condições da garantia"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=5000, verbose_name="Observações"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "odometer_reading",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service",
                        to="garage.odometerreading",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="garage.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(models.F("date"), descending=True, nulls_last=True),
                    "-pk",
                ],
            },
        ),
        migrations.CreateModel(
            name="ServicePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Peça")),
                (
                    "brand_model",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Marca, modelo ou código",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="maintenance.servicerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="resolved_by_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_problems",
                to="maintenance.servicerecord",
                verbose_name="Serviço relacionado",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=200, upload_to=maintenance.models.attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=200)),
                ("content_type", models.CharField(max_length=50)),
                ("size", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="maintenance.problem",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="maintenance.servicerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("problem__isnull", True), ("service__isnull", False)
                            ),
                            models.Q(
                                ("problem__isnull", False), ("service__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="attachment_single_owner",
                    )
                ],
            },
        ),
    ]
