# Generated by Django 5.2.17 on 2026-09-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerecord",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="planning.maintenanceplan",
                verbose_name="Item do plano realizado",
            ),
        ),
    ]
