# Generated by Django 5.2.17 on 2026-09-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("garage", "0002_alter_odometerreading_source_alter_vehicle_fuel"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urban_traffic",
                    models.BooleanField(
                        default=False, verbose_name="Trânsito urbano com anda-e-para"
                    ),
                ),
                (
                    "short_trips",
                    models.BooleanField(
                        default=False,
                        verbose_name="Trajetos curtos, com o motor ainda frio",
                    ),
                ),
                (
                    "highway",
                    models.BooleanField(
                        default=False, verbose_name="Viagens em rodovia"
                    ),
                ),
                (
                    "parked_days",
                    models.BooleanField(
                        default=False, verbose_name="Fica parado vários dias seguidos"
                    ),
                ),
                (
                    "frequent_load",
                    models.BooleanField(
                        default=False,
                        verbose_name="Transporta carga ou equipamentos com frequência",
                    ),
                ),
                (
                    "rough_roads",
                    models.BooleanField(
                        default=False, verbose_name="Ruas esburacadas ou de terra"
                    ),
                ),
                (
                    "dusty_roads",
                    models.BooleanField(
                        default=False, verbose_name="Locais com muita poeira"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_profile",
                        to="garage.vehicle",
                    ),
                ),
            ],
        ),
    ]
